blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/santoshyadavdev/ngx-pwa-offline/discussions/categories/q-a
    about: The issue tracker is not intended for support. A new GitHub "Discussions" tab, with a Questions & Answers category, is available for that purpose.
  - name: Feature requests
    url: https://github.com/santoshyadavdev/ngx-pwa-offline/discussions/554
    about: Feature requests are no longer accepted.
